# np.zeros- returns an array with zero only
# np.ones-returns an array with one only
# np.full- array with desired number
# np.full((row,col),desired No)
# np.eye()-identity matrix
# np.arange()-similar to range function
# np.linspace()-evenly divides the array.

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

# checking array properties

In [ ]:

# arr.shape-return shape of array
# arr.size- return total element
# arr.ndim- return dimention of an array
# arr.dtype- return return data type
# type(arr)-return array dimension

In [19]:
arr=np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
arr.shape

(2, 3)

In [21]:
arr.size

6

In [22]:
arr.ndim

2

In [23]:
arr.dtype

dtype('int64')

# Changing datatype

In [33]:
arr=np.array([1.1,2.2,3.3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [34]:
arr=np.array([1.1,2.2,3.3])
arr1=arr.astype(np.int64)
arr1

array([1, 2, 3])

In [36]:
arr=np.array([[1,3,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  3,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr.shape

(4, 3)

In [38]:
arr.size

12

In [40]:
my_arr=arr.reshape(3,4)
my_arr

array([[ 1,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr.reshape(6,2)

array([[ 1,  3],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
arr.reshape(12,1)

array([[ 1],
       [ 3],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [43]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
my_arr=arr.flatten()
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr=np.array([50,60,70,80,90,55])

In [58]:
print(arr.dtype)
int(arr[0])

int64


50

In [57]:
int(arr[3])

80

In [59]:
int(arr[-1])

55

In [65]:
arr[5]

np.int64(55)

In [61]:
arr[1:6]

array([60, 70, 80, 90, 55])

In [63]:
arr[3:6]

array([80, 90, 55])

In [64]:
arr[3:]

array([80, 90, 55])

In [66]:
my_array=np.array([1,2,3,4,5,6])
print(my_array)
new_array=my_array[0:4]
print(new_array)
new_array[0]=100
print(new_array)
print(my_array)

[1 2 3 4 5 6]
[1 2 3 4]
[100   2   3   4]
[100   2   3   4   5   6]
